### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ShintaroNippon** [segunolalive/helloBooks#60]
Hi there, thanks for the web app...

But I have this issue!

I have installed in a production Heroku environment with name
https://upbibliotecaonline.herokuapp.com/signup

I ran the migrations on heroku cli... following 
heroku run sequelize db:migrate --env production -m --app upbibliotecaonline

But I can't make login in or sign up

Can you give have a look? 
What I'm I missing?

Sorry, bother.
Thanks
Carlos Vieira

**Comment by segunolalive** [comment]
Can you check your logs? There should be a stack trace in your heroku logs

**Comment by ShintaroNippon** [comment]
HI, thanks by the reply...
I got this

```
2019-05-03T20:05:38.127143+00:00 app[web.1]: Executing (default): SELECT "id", "firstName", "lastName", "email", "username", "password", "isAdmin", "membershipType", "passwordResetToken", "authId", "createdAt", "updatedAt" FROM "Users" AS "User" WHERE "User"."username" = 'carlos' LIMIT 1;
2019-05-03T20:05:38.212927+00:00 app[web.1]: Error: secretOrPrivateKey must have a value
2019-05-03T20:05:38.212931+00:00 app[web.1]: at Object.module.exports [as sign] (/app/node_modules/jsonwebtoken/sign.js:70:20)
2019-05-03T20:05:38.212935+00:00 app[web.1]: at getJWT (/app/dist/server/helpers/helpers.js:47:33)
2019-05-03T20:05:38.212936+00:00 app[web.1]: at /app/dist/server/controllers/UserController.js:172:41
2019-05-03T20:05:38.213690+00:00 app[web.1]: at <anonymous>POST /api/v1/users/signin 500 149.845 ms - 57
```


```

api/v1/users/signin:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
sw.js:25 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at sw.js:25
```

Thanks in advance
Carlos Vieira

**Comment by ShintaroNippon** [comment]
```
Executing (default): INSERT INTO "Users" ("id","firstName","lastName","email","username","password","isAdmin","membershipType","createdAt","updatedAt") VALUES (DEFAULT,'Carlos Manuel','Vieira','carlosvvd+1@gmail.com','carlosvieira','$2a$10$WZvh73w7pSokdiogyd/F/erTLg.7n04B4ABylWPimWcBIH.CE0Zka',false,'bronze','2019-05-03 20:10:43.293 +00:00','2019-05-03 20:10:43.293 +00:00') RETURNING *;
2019-05-03T20:10:43.409079+00:00 app[web.1]: Error: secretOrPrivateKey must have a value
2019-05-03T20:10:43.409083+00:00 app[web.1]: at Object.module.exports [as sign] (/app/node_modules/jsonwebtoken/sign.js:70:20)

```

**Comment by segunolalive** [comment]
Add a `SECRET` to your environment. This would be the JWT secret. set the value to something random and difficult to guess

Also add `JWT_EXPIRATION`. It's number of seconds you want the token to be active for.

**Comment by segunolalive** [comment]
These should have been included in the `.env.example` file

Sorry about that

**Comment by segunolalive** [comment]
Actually, there are a few other things that need to be documented. I haven't gotten around to doing that

**Comment by ShintaroNippon** [comment]
i already found the issue.. tis the jwtoken parameters

already online 
thanks

but i have other issue

how can i hava access as admin to add books ?

thanks

**Comment by ShintaroNippon** [comment]
set asAdmin as true
